AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Sample SAM Template for Event Bridge Examples\n"
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: AllowLambdaGlobal
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:*
            - s3:*
            - sns:*
            - events:*
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Resource: '*'
  SNSEvents:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Sub: ${AWS::StackName}-events-topic
      TopicName:
        Fn::Sub: ${AWS::StackName}-events-topic
  ExampleOne:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-example-one
      CodeUri: s3://coins-artifacts/builds/6d2ff196f826d7d233d3ba72b8051553
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 900
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Environment:
        Variables:
          SNS_NAME:
            Ref: SNSEvents
  ExampleTwo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-example-two
      CodeUri: s3://coins-artifacts/builds/2d717cc505b8e732e31d92b5f8a1fa85
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 900
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
  SNSEventsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: SNSEvents
      FunctionName:
        Fn::GetAtt:
        - ExampleTwo
        - Arn
  SNSSubscriptionExample:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Fn::GetAtt:
        - ExampleTwo
        - Arn
      Protocol: lambda
      TopicArn:
        Ref: SNSEvents
      FilterPolicy: '{"period": ["weekly"]}'
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: EventRule
      EventPattern:
        source:
        - custom.example
        detail-type:
        - transaction
        detail:
          period:
          - weekly
      Targets:
      - Arn:
          Fn::GetAtt:
          - ExampleTwo
          - Arn
        Id: EventsToInvokeLambda
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - ExampleTwo
        - Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - EventRule
        - Arn
  ExampleOneLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - /
        - - /aws/lambda
          - Ref: ExampleOne
      RetentionInDays: 5
  ExampleTwoLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - /
        - - /aws/lambda
          - Ref: ExampleTwo
      RetentionInDays: 5
